# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T07:47:47+00:00



import argparse
import json
import os
from datetime import datetime
from typing import *
from typing import Optional

from autogen.mcp.mcp_proxy import MCPProxy
from autogen.mcp.mcp_proxy.security import BaseSecurity, UnsuportedSecurityStub
from fastapi import Path, Query

from models import (
    AppointmentBookModel,
    AppointmentInitialModel,
    AppointmentInitialViewModel,
    AppointmentListViewModel,
    AppointmentNoShowModel,
    AppointmentRescheduleModel,
    AppointmentReserveModel,
    AppointmentViewModel,
    AvailabilityDayViewModel,
    AvailabilityViewModel,
    BookingFieldListViewModel,
    ConsumerV1CustomersCountriesGetResponse,
    ConsumerV1CustomersStatesGetResponse,
    CustomerInputModel,
    CustomerListViewModel,
    CustomerUpdateModel,
    CustomerViewModel,
    CustomFieldDefinitionListViewModel,
    LocationListViewModel,
    LocationViewModel,
    ResourceGroupListViewModel,
    ResourceGroupViewModel,
    ResourceListViewModel,
    ResourceServiceListViewModel,
    ResourceViewModel,
    ServiceAllocationListViewModel,
    ServiceAllocationViewModel,
    ServiceGroupListViewModel,
    ServiceGroupViewModel,
    ServiceListViewModel,
    ServiceSortOrder,
    ServicesScope,
    ServiceViewModel,
    UnavailableTimeListViewModel,
)

app = MCPProxy(
    description="Build secure and scalable custom apps for Online Booking. Our flexible API provides many options for availability and booking.\r\n<br><br>\r\nTake the API for a test drive. Just click on the Authorize button below and authenticate. \r\nYou can access our demo company profile if you are not a customer, or your own profile by using your assigned ClientId and Secret.\r\n<br><br>\r\nThe API has two interfaces, consumer and setup. \r\n<ul>\r\n<li>\r\nThe consumer interface provides all the endpoints required for implementing consumer booking flows.\r\n</li>\r\n<li>\r\nThe setup interface provides endpoints for profile configuration and setup.\r\n</li>\r\n</ul>\r\nToggle freely between the two interfaces using the swagger tool bar option labelled 'Select a definition'.\r\n",
    title='OnSched Consumer API',
    version='v1',
    servers=[{'url': 'https://sandbox-api.onsched.com/'}],
)


@app.get(
    '/consumer/v1/appointments',
    description=""" <p>Use this endpoint to return a <b>List of Appointments</b>. Use the offset and limit parameters to control the page start and number of results. Default offset is 0, limit is 20, max is 100. Use the query parameters to filter the results further. For more information: <a href="https://onsched.readme.io/docs/appointments-overview">Appointments Overview</a></p> """,
    tags=[
        'appointment_management',
        'customer_data_management',
        'service_availability_management',
        'location_data_management',
        'resource_group_management',
        'service_details_management',
    ],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def get_consumer_v1_appointments(
    location_id: Optional[str] = Query(None, alias='locationId'),
    email: Optional[str] = None,
    lastname: Optional[str] = None,
    phone: Optional[str] = None,
    service_id: Optional[str] = Query(None, alias='serviceId'),
    calendar_id: Optional[str] = Query(None, alias='calendarId'),
    resource_id: Optional[str] = Query(None, alias='resourceId'),
    customer_id: Optional[str] = Query(None, alias='customerId'),
    service_allocation_id: Optional[str] = Query(None, alias='serviceAllocationId'),
    start_date: Optional[datetime] = Query(None, alias='startDate'),
    end_date: Optional[datetime] = Query(None, alias='endDate'),
    status: Optional[str] = None,
    booked_by: Optional[str] = Query(None, alias='bookedBy'),
    offset: Optional[int] = None,
    limit: Optional[int] = None,
):
    """
    Get Appointments
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/consumer/v1/appointments',
    description=""" <p>Use this endpoint to <b>Create</b> a new appointment. The appointment will be created with an "IN", Initial status. Posting an appointment with "IN" status requires minimal information and requires a "PUT book" call to complete the booking transaction, <i>PUT ​/consumer​/v1​/appointments​/{id}​/book</i>. Alternatively, you can post an appointment using the <b>completeBooking</b> option which completes the booking in one transaction, but it will require more data. The method you choose depends on your solutions workflow. </p>
<p>
  <b>StartDateTime</b> and <b>EndDateTime</b> are required. Use the ISO 8601 format for DateTime Timezone, e.g., <b>2016-10-30T09:00:00-5:00</b></p>
<p>A valid <b>serviceId</b> is required. The serviceId provided must be valid for the location being booked. A valid serviceId is one that is scoped to a Primary Company Location or is associated with a Business Location</p>
<p>OPTIONAL FIELDS INCLUDE: </p>
<p>
  <b>locationId</b> - if not supplied, the appointment will be posted to the primary business location. If you support multiple location, we recommend always supplying the locationId. </p>
<p>
  <b>resourceId</b> - not required when posting with an "IN" status but is required when the appointment is booked. Use <i>GET /consumer/v1/resources</i> for a list of resources. </p>
<p>
  <b>customerId</b> - if supplied the name and email will be retrieved from the customer record. </p>
<p>
  <b>BookedBy</b> - if not supplied the email address of the booked appointment is used or the ip address if no email address is provided. BookedBy is used in the Appointment Audit trail which can be viewed in the appointment object.</p>
<p>
  <b>Location</b> - is a string value representing the location of the appointment. It provides no added functionality in OnSched and should not be confused with locationId.</p>
<p>
  <b>TimezoneName</b> - if used timezoneName must be in IANA format, <i>America/New_York</i>. This is the timezone the appointment was booked in. Populating this information can help later in situations where appointments are booked before a Daylight Savings change. If no timezoneName is supplied, the Business Locations timezone will be used.</p>
<p>
  <b>COMPLETE BOOKING:</b> This parameter provides a mechanism for immediate booking with the POST appointment endpoint. To complete the booking in one transaction, populate the <b>completeBooking</b> parameter with a "BK", booked or an "RS", reserved status and provide an (<b>email</b> and <b>name</b>) or a <b>customerId</b> in the post body. Doing so will book the appointment and send notifications all in one transaction. <b>Note:</b> "IN" can also be used as a completeBooking option to support payment flows. With the "IN" option, notifications are NOT sent.</p>
<p>For more information: <a href="https://onsched.readme.io/docs/appointments-overview">Appointments Overview</a></p> """,
    tags=['appointment_management'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def post_consumer_v1_appointments(
    complete_booking: Optional[str] = Query(None, alias='completeBooking'),
    body: AppointmentInitialModel = None,
):
    """
    Create Appointment
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/consumer/v1/appointments/bookingfields',
    description=""" <p>Use this endpoint to return a locations <b>Appointment Booking Fields</b>. Appointment booking fields are stored with each Appointment record. They are used when you need additional information collected during your booking process. It is tied to an appointment/visit and will be stored in the appointment record. Use the field name, type, and length to determine how to update these field values when posting an appointment.</p> """,
    tags=['location_data_management'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def get_consumer_v1_appointments_bookingfields(
    location_id: Optional[str] = Query(None, alias='locationId')
):
    """
    Get Custom Fields Labels
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/consumer/v1/appointments/customfields',
    description=""" <p>Use this endpoint to return a locations <b>Appointment Custom Field</b> definitions. Appointment custom fields are stored with each appointment. They are used when the information collected during the booking is specific to a particular appointment/visit. The response will list the custom fields used (customField1 - 10), the field type (string, number, date, boolean) and the length of each one.</p> """,
    tags=['location_data_management'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def get_consumer_v1_appointments_customfields(
    location_id: Optional[str] = Query(None, alias='locationId')
):
    """
    Get Custom Fields List
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/consumer/v1/appointments/{id}',
    description=""" <p>Use this endpoint to permanently <b>Delete</b> an appointment. Only appointments with a of "IN" status, initial, can be deleted. Past dated appointments cannot be deleted. A valid <b>appointment id</b> is required. Use the appointment id returned from the initial <i>POST /consumer/v1/appointments</i> endpoint.</p>
<p>For more information: <a href="https://onsched.readme.io/docs/appointments-overview">Appointment Overview</a></p> """,
    tags=['appointment_management'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def delete_consumer_v1_appointments__id(id: str):
    """
    Delete Appointment
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/consumer/v1/appointments/{id}',
    description=""" <p>Use this endpoint to return an <b>Appointment</b> object. A valid <b>appointment id</b> is required. For more information: <a href="https://onsched.readme.io/docs/appointments-overview">Appointments Overview</a></p> """,
    tags=['appointment_management'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def get_consumer_v1_appointments__id(id: str):
    """
    Get Appointment
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.put(
    '/consumer/v1/appointments/{id}/book',
    description=""" <p>Use this endpoint to <b>Book</b> an appointment. Only appointments with an "IN" status, Initial, can be booked. A valid <b>appointment id</b> is required. Use the appointment id returned from the initial <i>POST /consumer/v1/appointments</i> endpoint. Other pertinent fields can also be updated at the time of booking by including them in the post body. <b>Note: If no name or email address was provided in the initial Post Appointment, it will be required in the post body.</b></p>
<p>For more information: <a href="https://onsched.readme.io/docs/appointments-overview">Appointments Overview</a></p> """,
    tags=['appointment_management'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def put_consumer_v1_appointments__id_book(id: str, body: AppointmentBookModel = None):
    """
    Book Appointment
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.put(
    '/consumer/v1/appointments/{id}/cancel',
    description=""" <p>Use this endpoint to <b>Cancel</b> an appointment booking or reservation. Only appointments with a "BK", booked or "RS", reserved status can be cancelled. Past dated appointments cannot be cancelled. A valid <b>appointment id</b> is required. For more information: <a href="https://onsched.readme.io/docs/appointments-overview">Appointment Overview</a></p> """,
    tags=['appointment_management'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def put_consumer_v1_appointments__id_cancel(id: str):
    """
    Cancel Appointment
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.put(
    '/consumer/v1/appointments/{id}/confirm',
    description=""" <p>Use this endpoint to <b>Confirm</b> an appointment. This updates the boolean confirmed field to TRUE. <b>NOTE:</b> If the appointment status is set to "RS", Reserved, it also updates the status of the appointment to "BK", Booked. </p>
<p>For more information: <a href="https://onsched.readme.io/docs/appointments-overview">Appointment Overview</a></p> """,
    tags=['appointment_management'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def put_consumer_v1_appointments__id_confirm(id: int, undo: Optional[bool] = None):
    """
    Confirm Appointment
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.put(
    '/consumer/v1/appointments/{id}/noshow',
    description=""" <p>Use this endpoint to change the status of an appointment from "BK", Booked to <b>"NS", NoShow</b>. This gives API consumers a way to internally track No Show appointments. It provides no added functionality in OnSched.</p>
<p>For more information: <a href="https://onsched.readme.io/docs/appointments-overview">Appointment Overview</a></p> """,
    tags=['appointment_management'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def put_consumer_v1_appointments__id_noshow(
    id: int, body: AppointmentNoShowModel = None
):
    """
    Set NoShow Status
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.put(
    '/consumer/v1/appointments/{id}/reschedule',
    description=""" <p>Use this endpoint to <b>Reschedule</b> an appointment booking. Only appointments in "BK", booked status, can be Rescheduled. Past dated appointments cannot be rescheduled. A valid <b>appointment id</b> is required.</p>
<p>The <b>StartDateTime</b> and <b>EndDateTime</b> are required. Use the ISO 8601 format for DateTime Timezone, e.g., <b>2016-10-30T09:00:00-5:00</b>.</p>
<p>The serviceId is optional. If changing the <b>serviceId</b>, the new service id's duration must match the original service's duration.</p>
<p>The resourceId is optional. If changing the <b>resourceId</b>, verify the availability of the new resource prior to rescheduling.</p>
<p>
  <b>IMPORTANT:</b> Always run availability before rescheduling an appointment to verify the timeslot is open and available for the new time, service and/or resource requested. This is the only way to assure the slot is available. You cannot reschedule an appointment to a different location. If necessary, you should cancel and then book an appointment in the other location.</p>
<p>For more information: <a href="https://onsched.readme.io/docs/appointments-overview">Appointment Overview</a></p> """,
    tags=['appointment_management'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def put_consumer_v1_appointments__id_reschedule(
    id: str, body: AppointmentRescheduleModel = None
):
    """
    Reschedule Appointment
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.put(
    '/consumer/v1/appointments/{id}/reserve',
    description=""" <p>Use this endpoint to <b>Reserve</b> an appointment. Only appointments with an "IN" status, Initial, can be reserved. A valid <b>appointment id</b> is required. Use the appointment id returned from the initial <i>POST /consumer/v1/appointments</i> endpoint.</p>
<p>
  <b>NOTE: Reservations are different from Bookings as reservations are a two-step booking process that must be managed by the API consumer.</b> An appointment that is reserved is not completely booked until other business conditions have been met. For example, an appointment may be reserved if it is not yet assigned to a resource or until the customer or resource explicitly confirms it.</p>
<p>With reservations you have the ability to notify the customer of a reservation prior to officially booking and the workflow can be designed to indicate what conditions will need to be met in order to convert the reservation to a complete booking. A reservation converts to a complete booking when it is either Confirmed or Booked. </p>
<p>
  <b>IMPORTANT: A reserved appointment time will not be released, i.e., become available to others, until it is Cancelled. The booking timer is not used with reserved appointments.</b>
</p>
<p>For more information: <a href="https://onsched.readme.io/docs/appointments-overview">Appointments Overview</a></p> """,
    tags=['appointment_management'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def put_consumer_v1_appointments__id_reserve(
    id: str,
    send_notifications: Optional[bool] = Query(None, alias='sendNotifications'),
    body: AppointmentReserveModel = None,
):
    """
    Reserve Appointment
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/consumer/v1/availability/{serviceId}/{startDate}/{endDate}',
    description=""" <p>
  <b>Choose your search criteria carefully. Availability is an expensive call.</b> If you search availability for all resources, you should only do so for a single date. If you search availability for multiple dates, you should only do so for a specific resource by specifying the optional resourceId parameter.</p>
<p>A <b>serviceId</b> is required. The <b>startDate</b> and <b>endDate</b> are required and are formatted as: <b>YYYY-MM-DD</b></p>
<p>A <b>resourceId</b> is optional, it is recommended if known at the time of availability call.</p>
<p>
  <b>timezoneName</b> is optional, it allows you to specify the IANA formatted name for the end user's timezone to view availability. e.g., <i>America/New_York</i>. <b>NOTE: This is the recommended approach for your implementation.</b>  The "tzOffset" parameter remains for backward compatibility.  For JavaScript, use moment.js in your client for ease of timezone detection and selection. For iOS, use the name property of the NSTimeZone returned from the localTimeZone method. For .NET, consider NodaTime or TimeZoneConverter via NuGet. </p>
<p>
  <b>duration</b> should only be populated if you allow the end user to select a duration, otherwise the service's duration will be used.</p>
<p>
  <b>startTime</b> and <b>endTime</b> are optional and are specified in <b>military time e.g., 800 = 8:00am, 2230 = 10:30pm</b>. Note: You will only see availability within the boundary of your business location start and end times.</p>
<p>
  <b>dayAvailability</b> will return day level availability for the number of days requested from the start date. See <i>GET /consumer/v1/availability/{serviceId}/{startDate}/{endDate}/days</i> for details.</p>
<p>
  <b>firstDayAvailable</b> only works with day availability. If set to true it will look for the first day available within the range specified by the dayAvailability parameter. The two parameters together can be a clever way to display availability for a week or month. Tip - pass in the beginning of the week or month, and available times are displayed for the first available date if exists.</p>
<p>
  <b>tzOffset</b> allows you to pass in the timezone offset for the end user's timezone of choice, e.g., (-240) for EST. If you use this option, your application should be timezone aware. The requested timezone is specified as an offset (plus or minus) from GMT time.</p>
<p>Availability can be complex. For further troubleshooting refer to the: <i><b>GET /consumer/v1/availability/{serviceId}/{startDate}/{endDate}/unavailable</b></i> endpoint. This endpoint will show you all unavailable times for a given date range. Available times are created from any unblocked time periods. For more information: <a href="https://onsched.readme.io/docs/availability-overview">Availability Overview</a></p> """,
    tags=['service_availability_management', 'appointment_management'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def get_consumer_v1_availability__service_id__start_date__end_date(
    service_id: str = Path(..., alias='serviceId'),
    start_date: datetime = Path(..., alias='startDate'),
    end_date: datetime = Path(..., alias='endDate'),
    start_time: Optional[int] = Query(None, alias='startTime'),
    end_time: Optional[int] = Query(None, alias='endTime'),
    location_id: Optional[str] = Query(None, alias='locationId'),
    resource_id: Optional[str] = Query(None, alias='resourceId'),
    resource_group_id: Optional[str] = Query(None, alias='resourceGroupId'),
    resource_ids: Optional[str] = Query(None, alias='resourceIds'),
    round_robin: Optional[str] = Query(None, alias='roundRobin'),
    duration: Optional[int] = None,
    interval: Optional[int] = None,
    timezone_name: Optional[str] = Query(None, alias='timezoneName'),
    tz_offset: Optional[int] = Query(None, alias='tzOffset'),
    destination: Optional[str] = None,
    day_availability_start_date: Optional[datetime] = Query(
        None, alias='dayAvailabilityStartDate'
    ),
    day_availability: Optional[int] = Query(None, alias='dayAvailability'),
    first_day_available: Optional[bool] = Query(None, alias='firstDayAvailable'),
):
    """
    Get Available Times
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/consumer/v1/availability/{serviceId}/{startDate}/{endDate}/days',
    description=""" <p>This endpoint will return <b>Day Level Availability</b> for the range of dates requested. For example, if the business is closed, or there is a public holiday this endpoint will return that the "Day is unavailable".</p>
<p>Day Availability is a high-level check for Holidays and Open/Available hours of a location, service and/or resource and should be used to restrict your choices of days available in your application to improve usability and performance.</p>
<p>A <b>serviceId</b> is required. The <b>startDate</b> and <b>endDate</b> are required and are formatted as: <b>YYYY-MM-DD</b></p>
<p>The locationId is optional, however if not supplied it defaults to the Primary Business Location for open/closed hours information. It is recommended you always provide the locationId.</p>
<p>A <b>resourceId</b> is optional. If used the available days will be return day availability for the resource specified.</p>
<p>The <b>tzOffset</b> parameter should be used if the appointment requester, the end user, is in a different timezone than the location or resource.</p> """,
    tags=[
        'service_availability_management',
        'location_data_management',
        'resource_group_management',
    ],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def get_available_days(
    service_id: str = Path(..., alias='serviceId'),
    start_date: datetime = Path(..., alias='startDate'),
    end_date: datetime = Path(..., alias='endDate'),
    location_id: Optional[str] = Query(None, alias='locationId'),
    resource_id: Optional[str] = Query(None, alias='resourceId'),
    tz_offset: Optional[int] = Query(None, alias='tzOffset'),
):
    """
    Get Available Days
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/consumer/v1/availability/{serviceId}/{startDate}/{endDate}/unavailable',
    description=""" <p>This endpoint is used to show <b>Unavailable</b> times and provides valuable information as to why a time slot is unavailable. If you question your availability results, populate the same parameters to this endpoint to find out why.</p>
<p>A <b>serviceId</b> is required. The <b>startDate</b> and <b>endDate</b> are required and are formatted as: <b>YYYY-MM-DD</b></p>
<p>Location hours, holidays, services, resources, blocks, allocations, and appointments are just some of variables that may cause time slots to become unavailable. Use this endpoint to understand why you don't see availability.</p> """,
    tags=['service_availability_management', 'appointment_management'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def get_unavailable_times(
    service_id: str = Path(..., alias='serviceId'),
    start_date: datetime = Path(..., alias='startDate'),
    end_date: datetime = Path(..., alias='endDate'),
    location_id: Optional[str] = Query(None, alias='locationId'),
    resource_id: Optional[str] = Query(None, alias='resourceId'),
    duration: Optional[int] = None,
    tz_offset: Optional[int] = Query(None, alias='tzOffset'),
    skip_time_past_unavailability: Optional[bool] = Query(
        None, alias='skipTimePastUnavailability'
    ),
):
    """
    Get Unavailable Times
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/consumer/v1/customers',
    description=""" <p>Use this endpoint to return a <b>List of Customers</b>. The results are returned in pages. Use the offset and limit parameters to control the page start and number of results. Default offset is 0, limit is 20, max is 100. Use the query parameters to filter the results further.</p> """,
    tags=['customer_data_management', 'location_data_management'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def get_consumer_v1_customers(
    location_id: Optional[str] = Query(None, alias='locationId'),
    group_id: Optional[str] = Query(None, alias='groupId'),
    email: Optional[str] = None,
    lastname: Optional[str] = None,
    deleted: Optional[bool] = None,
    offset: Optional[int] = None,
    limit: Optional[int] = None,
):
    """
    List Customers
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/consumer/v1/customers',
    description=""" <p>Use this endpoint to <b>Create</b> a new Customer. A customer object is automatically created with the first appointment booking if it doesn't already exist. If not specified, the business location id defaults to the primary business location.</p>
<p>Required Fields: <b>Email</b> and <b>Name</b> or <b>First and Lastname</b> depending on customer type. Type 0 = Person, Type 1 = Business. For type 0, the firstname and lastname fields are used. For type 1, the Name field is used, and the name field is also used to populate the lastname.</p> """,
    tags=['customer_data_management'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def post_consumer_v1_customers(body: CustomerInputModel = None):
    """
    Create Customer
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/consumer/v1/customers/bookingfields',
    description=""" <p>Use this endpoint to return <b>Customer Booking Fields</b>. Customer booking fields are stored with each customer object. They are used when the information collected during the booking is for a particular customer. Customer Booking Fields include any custom customer fields you define and want to capture with the Booking.</p> """,
    tags=['location_data_management', 'customer_data_management'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def get_consumer_v1_customers_bookingfields(
    location_id: Optional[str] = Query(None, alias='locationId')
):
    """
    Get Customer Booking Fields
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/consumer/v1/customers/countries',
    description=""" <p>Use this endpoint to return a <b>List of Countries with their associated Country Code</b>. Country codes are based on the 2-character ANSI standard. If your countries of operation are not currently listed, contact us at <i><b>support@onsched.com</b></i>.</p> """,
    tags=['location_data_management'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def get_consumer_v1_customers_countries():
    """
    List Country Codes
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/consumer/v1/customers/customfields',
    description=""" <p>Use this endpoint to return <b>Customer Custom Fields</b>. Customer custom fields are stored with the customer object. They are used when the information collected during the booking is specific to a particular customer.</p> """,
    tags=['customer_data_management', 'location_data_management'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def get_consumer_v1_customers_customfields(
    location_id: Optional[str] = Query(None, alias='locationId'),
    lead_questions: Optional[bool] = Query(None, alias='leadQuestions'),
):
    """
    Get Customer Custom Fields
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/consumer/v1/customers/states',
    description=""" <p>Use this endpoint to return a <b>List of Countries with their associated State Codes</b>. Supply a country code to filter results further. If states for your countries of operation are not currently listed, contact us at <i><b>support@onsched.com</b></i>.</p> """,
    tags=['location_data_management'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def get_consumer_v1_customers_states(country: Optional[str] = None):
    """
    List Country States
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/consumer/v1/customers/{id}',
    description=""" <p>Use this endpoint to permanently <b>Delete</b> a Customer object. A valid <b>customer id</b> is required.</p> """,
    tags=['customer_data_management'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def delete_consumer_v1_customers__id(id: str):
    """
    Delete Customer
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/consumer/v1/customers/{id}',
    description=""" <p>Use this endpoint to return a <b>Customer</b> object. A valid <b>customer id</b> is required. Find customer id's by using the <i>GET /consumer/v1/customers</i> endpoint.</p> """,
    tags=['customer_data_management'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def get_consumer_v1_customers__id(id: str):
    """
    Get Customer
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.put(
    '/consumer/v1/customers/{id}',
    description=""" <p>Use this endpoint to <b>Update</b> a Customer object. A valid <b>customer id</b> is required. Note: Blank fields are not changed.</p> """,
    tags=['customer_data_management'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def put_consumer_v1_customers__id(id: str, body: CustomerUpdateModel = None):
    """
    Update Customer
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/consumer/v1/locations',
    description=""" <p>Use this endpoint to return a <b>List of Business Locations</b>. The results are returned in pages. Use the offset and limit parameters to control the page start and size. Default offset is 0, and limit is 20 and maximum is 100. Use the other query parameters to filter the results further. </p>
<p>
  <b>IMPORTANT DEPRECATION NOTICE</b>: The following online settings parameters were intended for internal use in our Portal application only. They will be deprecated on <b>OCTOBER 15, 2022</b>. These fields are currently part of the <b>SETTINGS</b> object in all location endpoints: <b>businessId, enabled, familyMembersEnabled, serviceLabel, resourceLabel, resourceAnyLabel, resourceSelection, liveMode, formFlow, availabilityForm, showServiceGroups, showOnSchedLogo, showBusinessLogo, disableAuthorization, hideNavBar, hideLocationNav, hideServiceGroupsNav, hideServicesNav, hideContinueBooking, returnToService, returnToAvailability, hideBreadCrumbNav.</b> If you are using these fields, please adjust your code to handle the deprecation or let us know by submitting a ticket to: <b><i>support@onsched.com</i></b> as we do not want to interrupt your existing workflows.</p> """,
    tags=['location_data_management'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def get_consumer_v1_locations(
    name: Optional[str] = None,
    nearest_to: Optional[str] = Query(None, alias='nearestTo'),
    proximity: Optional[int] = None,
    units: Optional[str] = None,
    service_id: Optional[str] = Query(None, alias='serviceId'),
    friendly_id: Optional[str] = Query(None, alias='friendlyId'),
    region_id: Optional[str] = Query(None, alias='regionId'),
    ignore_primary: Optional[bool] = Query(None, alias='ignorePrimary'),
    offset: Optional[int] = None,
    limit: Optional[int] = None,
):
    """
    List Locations
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/consumer/v1/locations/{id}',
    description=""" <p>Use this endpoint to return a <b>Location</b> object. A valid business <b>location id</b> is required. Find all location id's by using the <i>GET /consumer/v1/locations</i> endpoint.</p>
<p>
  <b>IMPORTANT DEPRECATION NOTICE</b>: The following online settings parameters were intended for internal use in our Portal application only. They will be deprecated on <b>OCTOBER 15, 2022</b>. These fields are currently part of the <b>SETTINGS</b> object in all location endpoints: <b>businessId, enabled, familyMembersEnabled, serviceLabel, resourceLabel, resourceAnyLabel, resourceSelection, liveMode, formFlow, availabilityForm, showServiceGroups, showOnSchedLogo, showBusinessLogo, disableAuthorization, hideNavBar, hideLocationNav, hideServiceGroupsNav, hideServicesNav, hideContinueBooking, returnToService, returnToAvailability, hideBreadCrumbNav.</b> If you are using these fields, please adjust your code to handle the deprecation or let us know by submitting a ticket to: <b><i>support@onsched.com</i></b> as we do not want to interrupt your existing workflows.</p> """,
    tags=['location_data_management'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def get_consumer_v1_locations__id(id: str):
    """
    Get Location
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/consumer/v1/resourcegroups',
    description=""" <p>Use this endpoint to return a list of <b>Resource Groups</b> for the requested location. If not specified, the business location defaults to the primary business location.</p> """,
    tags=['resource_group_management', 'location_data_management'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def get_consumer_v1_resourcegroups(
    location_id: Optional[str] = Query(None, alias='locationId'),
    deleted: Optional[bool] = None,
    offset: Optional[int] = None,
    limit: Optional[int] = None,
):
    """
    List Resource Groups
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/consumer/v1/resourcegroups/{id}',
    description=""" <p>Use this endpoint to return a <b>Resource Group</b> object. A valid <b>resourceGroup id</b> is required. Find resourceGroup id's by using the <i>GET /consumer/v1/resourceGroups</i> endpoint.</p> """,
    tags=['resource_group_management'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def get_consumer_v1_resourcegroups__id(id: str):
    """
    Get Resource Group
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/consumer/v1/resources',
    description=""" <p>Use this endpoint to return a <b>List of Resources</b> associated with a business location. If not specified, the business location defaults to the primary business location. The results are returned in pages. Use the offset and limit parameters to control the page start and number of results. Default offset is 0, limit is 20, max is 100. Use the query parameters to filter the results further.</p> """,
    tags=['resource_group_management', 'location_data_management'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def get_consumer_v1_resources(
    location_id: Optional[str] = Query(None, alias='locationId'),
    resource_group_id: Optional[int] = Query(None, alias='resourceGroupId'),
    email: Optional[str] = None,
    name: Optional[str] = None,
    sort_order: Optional[str] = Query(None, alias='sortOrder'),
    offset: Optional[int] = None,
    limit: Optional[int] = None,
):
    """
    List Resources
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/consumer/v1/resources/{id}',
    description=""" <p>Use this endpoint to return a <b>Resource</b> object. A valid <b>resource id</b> is required. Find resource id's by using the <i>GET consumer/v1/resources</i> endpoint. </p> """,
    tags=['resource_group_management'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def get_consumer_v1_resources__id(id: int):
    """
    Get Resource
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/consumer/v1/resources/{id}/services',
    description=""" <p>Use this endpoint to get a <b>List of Linked Services</b> associated with the resource requested. The results are returned in pages. Use the offset and limit parameters to control the page start and size. Default offset is 0, limit is 20, the maximum limit is 100. Use the other query parameters to filter the results further.</p>
<p>Resource linked services are used to explicitly define the services that can be booked for a specified resource. By default, all services are bookable for any resource. For more information: <a href="https://docs.onsched.com/docs/linked-services">Linked Services Overview</a></p> """,
    tags=['resource_linkage_to_services', 'resource_group_management'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def get_consumer_v1_resources__id_services(
    id: int, offset: Optional[int] = None, limit: Optional[int] = None
):
    """
    Get Resource Linked Services
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/consumer/v1/servicegroups',
    description=""" <p>Use this endpoint to return a list of <b>Service Groups</b> for the requested location. If not specified, the business location defaults to the primary business location. Use the offset and limit parameters to control the page start and size. Default offset is 0, limit is 20, maximum is 100. Use the other query parameters to filter the results further.</p> """,
    tags=['service_group_data_management', 'location_data_management'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def get_consumer_v1_servicegroups(
    location_id: Optional[str] = Query(None, alias='locationId'),
    offset: Optional[int] = None,
    limit: Optional[int] = None,
):
    """
    List Service Groups
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/consumer/v1/servicegroups/{id}',
    description=""" <p>Use this endpoint to return a <b>Service Group</b> object. A valid <b>serviceGroup id</b> is required. Find serviceGroup id's by using the <i>GET /consumer/v1/serviceGroups</i> endpoint.</p> """,
    tags=['service_group_data_management', 'resource_group_management'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def get_consumer_v1_servicegroups__id(id: int):
    """
    Get Service Group
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/consumer/v1/services',
    description=""" <p>Use this endpoint to <b>List Services</b> available at your business location and/or company. If not specified, the business location defaults to the primary business location. Use the offset and limit parameters to control the page start and number of results. Default offset is 0, limit is 20, max is 100. Use the query parameters to filter the results further.</p> """,
    tags=[
        'service_details_management',
        'service_availability_management',
        'service_group_data_management',
    ],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def get_consumer_v1_services(
    location_id: Optional[str] = Query(None, alias='locationId'),
    service_group_id: Optional[int] = Query(None, alias='serviceGroupId'),
    default_service: Optional[bool] = Query(None, alias='defaultService'),
    all_locations: Optional[bool] = Query(None, alias='allLocations'),
    scope: Optional[ServicesScope] = None,
    name: Optional[str] = None,
    service_id: Optional[str] = Query(None, alias='serviceId'),
    offset: Optional[int] = None,
    limit: Optional[int] = None,
    sort_order: Optional[ServiceSortOrder] = Query(None, alias='sortOrder'),
    sort_descending: Optional[bool] = Query(None, alias='sortDescending'),
):
    """
    List Services
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/consumer/v1/services/allocations/{id}',
    description=""" <p>Use this endpoint to return a <b>Service Allocation</b> object. A valid <b>serviceAllocation id</b> is required. Find service allocation id's by using the <i>GET/consumer​/v1​/services​/{id}​/allocations</i> endpoint.</p> """,
    tags=['service_allocation_tracking', 'service_details_management'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def get_consumer_v1_services_allocations__id(id: str):
    """
    Get Service Allocation
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/consumer/v1/services/{id}',
    description=""" <p>Use this endpoint to return a <b>Service</b> object. A valid <b>service id</b> is required. Find service id's by using the <i>GET /consumer/v1/services</i> endpoint.</p> """,
    tags=['service_details_management', 'service_group_data_management'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def get_consumer_v1_services__id(id: int):
    """
    Get Service
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/consumer/v1/services/{id}/allocations',
    description=""" <p>Use this endpoint to return a <b>List of Service Allocations</b> associated with the requested service. A valid <b>service id</b> is required. Allocations are used for Event type services/bookings. Retrieve all allocations for a location by passing in zero as the service id. Otherwise, to get allocations for a specific service supply the service id. Use the offset and limit parameters to control the page start and number of results. Default offset is 0, limit is 20, max is 100. Use the query parameters to filter the results further. For more information: <a href="https://docs.onsched.com/reference/post_setup-v1-services-id-allocations">Create Service Allocations</a></p> """,
    tags=['service_allocation_tracking'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def get_consumer_v1_services__id_allocations(
    id: str,
    location_id: Optional[str] = Query(None, alias='locationId'),
    resource_id: Optional[str] = Query(None, alias='resourceId'),
    start_date: Optional[datetime] = Query(None, alias='startDate'),
    end_date: Optional[datetime] = Query(None, alias='endDate'),
    offset: Optional[int] = None,
    limit: Optional[int] = None,
):
    """
    List Service Allocations
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/consumer/v1/services/{id}/resources',
    description=""" <p>Use this endpoint to return a list of <b>Resources that provide the Service requested</b>. A valid <b>service id</b> is required. The results are returned in pages. Use the offset and limit parameters to control the page start and number of results. Default offset is 0, limit is 20, max is 100. Use the query parameters to filter the results further.</p> """,
    tags=[
        'resource_group_management',
        'service_details_management',
        'resource_linkage_to_services',
    ],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def get_consumer_v1_services__id_resources(
    id: str,
    location_id: Optional[str] = Query(None, alias='locationId'),
    offset: Optional[int] = None,
    limit: Optional[int] = None,
):
    """
    List Resources for Service
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="MCP Server")
    parser.add_argument(
        "transport",
        choices=["stdio", "sse", "streamable-http"],
        help="Transport mode (stdio, sse or streamable-http)",
    )
    args = parser.parse_args()

    if "CONFIG_PATH" in os.environ:
        config_path = os.environ["CONFIG_PATH"]
        app.load_configuration(config_path)

    if "CONFIG" in os.environ:
        config = os.environ["CONFIG"]
        app.load_configuration_from_string(config)

    if "SECURITY" in os.environ:
        security_params = BaseSecurity.parse_security_parameters_from_env(
            os.environ,
        )

        app.set_security_params(security_params)

    mcp_settings = json.loads(os.environ.get("MCP_SETTINGS", "{}"))

    app.get_mcp(**mcp_settings).run(transport=args.transport)
